name: .NET

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/dotnet.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install Coverlet
        run: dotnet tool install --global coverlet.console

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test with coverage
        run: |
          dotnet test --collect:"XPlat Code Coverage" --results-directory TestResults
          reportgenerator "-reports:TestResults/**/coverage.cobertura.xml" "-targetdir:TestResults/Coverage" -reporttypes:Html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./TestResults/**/coverage.cobertura.xml
          flags: unittests
          name: code-coverage-report
          fail_ci_if_error: true
