name: .NET

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/dotnet.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install Coverlet
      run: dotnet tool install --global coverlet.console
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --collect:"XPlat Code Coverage" --results-directory TestResults
    - name: Generate coverage report
      run: reportgenerator -reports:TestResults/*/coverage.cobertura.xml -targetdir:TestResults/CoverageReport
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: TestResults/CoverageReport
