name: .NET

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main" 
    paths:
      - ".github/workflows/dotnet.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=TestResults/lcov.info
    - name: Upload report to codecov
      uses: codecov/codecov-action@v2
      with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./coverage.xml
            flags: tests
            name: codecov-placeholder-service
            fail_ci_if_error: true
            verbose: true 
      
